### ISSUE TITLE
PA Review: User Authentification

### ISSUE THREAD

**Issue by Bogdan18b** [Bogdan18b/Project_Ike#1]
1. - [x] Backend: DB, model, controller, views
2. - [ ] Frontend: ajax, actions, reducers, store
3. - [ ] Frontend: Presentational Components and Containers
4. - [ ] Styling
5. - [ ] Smooth, bug-free navigation
6. - [ ] Adequate and appropriate seeds

**Comment by m1010j** [comment]
- [ ] Your zip code input should be of type text.
